<?php

/**
 * Implements hook_menu()
 */
function ngmenu_menu() {
  $item = array();
  $item['menu'] = array
  (
    'title' => 'Angular menu page',
    //'access callback' => TRUE,
    'access arguments' => array('access content'),
    'page callback' => 'menu_callback',
    'cache' => DRUPAL_NO_CACHE,
  );

  return $item;
}

/**
 * hook theme()
 */
function ngmenu_theme(){
  return array(
    'gs2_theme' => array(
      'template' => 'gs2_menu',
    ),
  );
}

/**
 * All cats callback
 */
function menu_callback() {
  angularjs_init_application('catsville');
  drupal_add_library('angularjs', 'angularjs');

  $path = drupal_get_path('module', 'ngmenu');
  drupal_add_js($path . '/js/app.js');
  return theme('gs2_theme');
}